const data = {
  products: [
    {
      item: "Chocolate Donut",
      slug: "chocolate-donut",
      catagory: "Donuts",
      image: "/images/donut1.jpg",
      price: 9.99,
      countInStock: 20,
      brand: "Krispy Kreme",
      rating: 4.5,
      numReviews: 4,
      description: "Freshly Baked Top of the Morning",
    },

    {
      item: "Red Velvet Cake",
      slug: "red velvet-cake",
      catagory: "Cake",
      image: "/images/velvet-cake.jpg",
      price: 14.99,
      countInStock: 17,
      brand: "Sasko",
      rating: 3.9,
      numReviews: 7,
      description: "Perfect Everytime",
    },
    {
      item: "Blueberry Pancakes",
      slug: "blu-pancakes",
      catagory: "Pancakes",
      image: "/images/pancakes.jpg",
      price: 19.99,
      countInStock: 40,
      brand: "Golden Cloud",
      rating: 4.0,
      numReviews: 10,
      description: "Filled with Flavor",
    },
    {
      item: "Apple Pie",
      slug: "apple-pie",
      catagory: "Pies",
      image: "/images/apple-pie.jpg",
      price: 14.99,
      countInStock: 12,
      brand: "SPAR",
      rating: 3.1,
      numReviews: 17,
      description: "Melts in your Mouth",
    },
  ],
};

export default data;
